### ISSUE TITLE
Using apollo-link-error

### ISSUE THREAD

**Issue by Jaikant** [molindo/react-apollo-network-status#10]
This library is neat. Thank you!

I just had a quick question comparing this to trying to roll up something similar using [apollo-link-error](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-error). 

What are your thoughts? 

My primary use case is to handle offline error gracefully.

**Comment by amannn** [comment]
Hi @Jaikant!

`apollo-link-error` essentially provides you a callback, which is invoked when an error is encountered.

`react-apollo-network-status` gives you access to the same error metadata, but additionally attaches information if there are currently any pending requests. Have a look at [the README](https://github.com/molindo/react-apollo-network-status#usage) to see the data structure you'll receive. Furthermore this library has a React integration, so you can consume error and loading events in a declarative way. With `apollo-link-error` you have to build some kind of bridge to get that information into React components.

To detect an error which results from the app not being able to reach your server, you can check `error.networkError.statusCode`: If `networkError` is set, but there's no `statusCode`, it should be because the client is offline.

I hope that helps!
