### ISSUE TITLE
HOC instead of render prop

### ISSUE THREAD

**Issue by zsolt-dev** [molindo/react-apollo-network-status#11]
Hello,

Thank you for this project.

I am having a use case when I cannot use a render prop (the components under NetworkStatusNotifier cannot be remounted (componentDidMount), but just updated with the current network status.

Render props creates new component each time...

I am trying to connect it with google analytics package react-ga and therefore my analytics is reinitialised each time. 

I use this package to know if all the queries are finished, so I can safely call ReactGA.pageview(url) and the correct page information (title...) will get submitted to analytics.

thank you

**Comment by zsolt-dev** [comment]
sorry, it looks like there is no need for HOC, closing...

**Comment by amannn** [comment]
Hi @zsolt-dev!

As you mentioned in your second comment, a HOC wouldn't make a difference here. If you really prefer one, you can build one on top of the render prop API.

You mentioned that you have a component which shouldn't remount when the network status changes. There's no difference between a render prop and a HOC API here. What is re-created on every render is the React _element_, but not the _component instance_ ([explanation](https://reactjs.org/blog/2015/12/18/react-components-elements-and-instances.html)). If your component is remounting unexpectedly, I guess it's because of something else in your app.
