### ISSUE TITLE
Update to react-apollo 3.x

### ISSUE THREAD

**Issue by atombender** [molindo/react-apollo-network-status#16]
Installing this package results in this mismatch:

```
warning " > react-apollo-network-status@2.0.0" has incorrect peer dependency "react-apollo@^2.0.0".
```

`react-apollo` is currently at 3.1.1.

**Comment by amannn** [comment]
Hi @atombender, thanks for opening this issue.

Yep, I didn't have time to upgrade this package yet. Apollo has switched to a new context, so this doesn't work with `react-apollo-network-status@2` and a change is required.

You can use [`react-apollo-network-status@1`](https://github.com/molindo/react-apollo-network-status/tree/583a00f6344e05edcfee90bee0823a7736f56021) in the meantime if you like, since it doesn't use context. It's fairly similar, but has a render props API instead of hooks.

I'm not sure when I'll be able to do the update to `react-apollo@3`, I'm pretty busy currently.

**Comment by derblitz** [comment]
Version 1.1 doesn't work for me:

Could not find a declaration file for module 'react-apollo-network-status'. '/home/.../Desktop/node_modules/react-apollo-network-status/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-apollo-network-status` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-apollo-network-status';`  TS7016

**Comment by amannn** [comment]
@derblitz That's expected, because `react-apollo-network-status@1` didn't have TypeScript support.

On a different note, I might have time the next week or the one after that to work on an upgrade to `react-apollo@3`.

**Comment by atombender** [comment]
Awesome, thanks!
