### ISSUE TITLE
Loading stuck when "cancelling" queries

### ISSUE THREAD

**Issue by maggo** [molindo/react-apollo-network-status#4]
First thanks for this library! I encountered this bug where the loading prop is stuck to true when quickly clicking around my interface and cancelling/unmounting a query during the request.

I looked into the reducer logic and it seems that onSuccess is never called and therefor doesn't reset numPendingRequests to 0

I'll set up a test case later, but wanted to report already in case you have an idea :)

**Comment by amannn** [comment]
Ah, I [had a similar story with apollo 1.0](https://github.com/apollographql/apollo-client/issues/2012) which was based on redux back then. I noticed that queries don't necessarily have a result or error action that is following its init action. For mutations this was no problem however.

Since the architecture of apollo 2.0 is now based on observables, there should be solution for this. I just did a quick experiment and I think I know how this can be fixed. I'll keep you posted.
