### ISSUE TITLE
Reset errors

### ISSUE THREAD

**Issue by electerious** [molindo/react-apollo-network-status#45]
I'm using `client.clearStore()` to reset the Apollo cache when the user signs out. I somehow assumed that this would also reset any errors in the status, but this isn't the case.

What is the recommended way to reset the errors without using a custom reducer (I would need to reimplement most of the existing reducers to add a reset action)?

Thanks!

**Comment by amannn** [comment]
Hi @electerious,

the network state (including the errors) is stored in React state and the `useApolloNetworkStatus` hook just observes the network events from Apollo. So you should be able to set a `key` on the component that uses the hook to reset the state when you need to.

Does that help?

**Comment by electerious** [comment]
Thanks for the tip. I will give it a try!

**Comment by electerious** [comment]
It's sadly not an option for me. Several hooks are depending on the status and I would need to move them down into another component just to reset the status state. I guess it would work, but it's kinda weird in my case.

I've checked the reducer and it's a great solution, because I'm transforming the status anyway. The reducer allows me to directly build the state I need.

But… I can't implement a reset with the reducer :( The reducer just returns the status and not the dispatch (https://github.com/molindo/react-apollo-network-status/blob/master/src/useApolloNetworkStatusReducer.ts#L40). I therefore can't dispatch custom actions. I've assumed that the reducer returns the same tuple as `useReducer`.

**Comment by amannn** [comment]
Hmm, I understand.

> The reducer just returns the status and not the dispatch function

Yep, that's true. The reason is that for `useReducer` it's the consumer who dispatches the state changes. In the case of `useApolloNetworkStatusReducer`, only the reducer is provided, but we handle the events from the Apollo link architecture. There is unfortunately no event when the cache is reset, as only events that are related to the network are dispatched.

So I'm afraid currently the solution with `key` is the best you can do. I can't really think of a good alternative. I also wouldn't want for `useApolloNetworkStatusReducer` to return a `dispatch` function, as it seems to me like this would be workaround solely for the use case of resetting the cache. Sorry :-/
